module.exports = {
	"PARSE_LOCATION_SUCCESS": 1,
	"PARSE_LOCATION_FAIL": 2,
	"MAKE_RESERVATION_SUCCESS": 3,
	"MAKE_RESERVATION_FAIL": 4,
	"GET_RESERVATION_SUCCESS": 5,
	"GET_RESERVATION_FAIL": 6,
	"MAKE_ARTICLE_SUCCESS": 7,
	"MAKE_ARTICLE_FAIL": 8,
	"GET_ARTICLE_SUCCESS": 9,
	"GET_ARTICLE_FAIL": 10
	
}